name: Deploy Angular App

on:
  push:
    branches:
    - dev
    - master
    paths:
    - ng/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 16.13.2
    - name: Install Node Dependencies
      working-directory: ./ng
      run: npm install
    - name: Install Angular CLI
      working-directory: ./ng
      run: npm install -g @angular/cli

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      working-directory: ./ng
      run: ./deploy.sh